// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220430010450_RelationshipMigration")]
    partial class RelationshipMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Producto", b =>
                {
                    b.Property<int>("Sku_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sku_Id"), 1L, 1);

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nombre_Producto")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Precio")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Sku_Id");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Domain.Proveedor", b =>
                {
                    b.Property<int>("Id_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proveedor"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Proveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("ProductoProveedor", b =>
                {
                    b.Property<int>("ProductoSku_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProveedorId_Proveedor")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ProductoSku_Id", "ProveedorId_Proveedor");

                    b.HasIndex("ProveedorId_Proveedor");

                    b.ToTable("ProductoProveedor");
                });

            modelBuilder.Entity("ProductoProveedor", b =>
                {
                    b.HasOne("Domain.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoSku_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
